version: "3"
services:
  front:
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 9327:80
    command: >
     sh -c "npm run build &&
            nginx -g 'daemon off;'"
